<form action="/index/addsave" method="post">
    <p>
        <label>Username</label>
        <input class="text-input" type="text" name="data[username]"/>
    </p>

    <div class="clear"></div>
    <p>
        <label>Password</label>
        <input class="text-input" type="password" name="data[password]"/>
    </p>

    <div class="clear"></div>
    <p>
        <input class="button" type="submit" value="Add"/>
    </p>
</form>